# Generated by Django 4.2.6 on 2023-11-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.TextField(max_length=200, unique=True)),
                ('family_name', models.TextField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['ingredient_name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.TextField(max_length=200, unique=True)),
                ('default_volume', models.FloatField(blank=True, null=True)),
                ('default_servings', models.IntegerField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='SubRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='enchante.recipe')),
                ('sub_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_recipe', to='enchante.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='SquarePan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_name', models.TextField(max_length=200)),
                ('pan_type', models.CharField(choices=[('ROUND', 'Round'), ('SQUARE', 'Square')], max_length=200)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'ordering': ['pan_name'],
                'abstract': False,
                'unique_together': {('pan_name', 'length', 'width', 'height')},
            },
        ),
        migrations.CreateModel(
            name='RoundPan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_name', models.TextField(max_length=200)),
                ('pan_type', models.CharField(choices=[('ROUND', 'Round'), ('SQUARE', 'Square')], max_length=200)),
                ('diameter', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'ordering': ['pan_name'],
                'abstract': False,
                'unique_together': {('pan_name', 'diameter', 'height')},
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('instruction', models.TextField()),
                ('trick', models.TextField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchante.recipe')),
            ],
            options={
                'ordering': ['recipe', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='RecipePan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchante.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchante.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchante.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='enchante.RecipeIngredient', to='enchante.ingredient'),
        ),
        migrations.CreateModel(
            name='PanServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('volume', models.FloatField()),
                ('servings', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(max_length=200, null=True)),
                ('store_name', models.TextField(max_length=200, null=True)),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('unit', models.TextField(max_length=200)),
                ('price', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enchante.ingredient')),
            ],
        ),
    ]
