# Generated by Django 4.2.6 on 2023-11-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchante', '0002_category_label_remove_ingredient_family_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_name', 'chef']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('recipe_name', 'chef')},
        ),
    ]
