# Generated by Django 4.2.6 on 2023-11-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchante', '0003_alter_recipe_options_recipe_chef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.CharField(max_length=200),
        ),
    ]
