# Generated by Django 4.2.6 on 2023-11-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enchante', '0004_alter_recipe_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_name', models.TextField(max_length=200)),
                ('pan_type', models.CharField(choices=[('ROUND', 'Round'), ('SQUARE', 'Square')], max_length=200)),
            ],
            options={
                'ordering': ['pan_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='roundpan',
            options={'ordering': ['pan_ptr']},
        ),
        migrations.AlterModelOptions(
            name='squarepan',
            options={'ordering': ['pan_ptr']},
        ),
        migrations.RemoveField(
            model_name='panserving',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='panserving',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='subrecipe',
            name='sub_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrecipe_set', to='enchante.recipe'),
        ),
        migrations.DeleteModel(
            name='RecipePan',
        ),
        migrations.AlterUniqueTogether(
            name='roundpan',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='squarepan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='panserving',
            name='pan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enchante.pan'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enchante.pan'),
        ),
        migrations.AddField(
            model_name='roundpan',
            name='pan_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enchante.pan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squarepan',
            name='pan_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enchante.pan'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='roundpan',
            unique_together={('pan_ptr', 'diameter', 'height')},
        ),
        migrations.AlterUniqueTogether(
            name='squarepan',
            unique_together={('pan_ptr', 'length', 'width', 'height')},
        ),
        migrations.RemoveField(
            model_name='roundpan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='roundpan',
            name='pan_name',
        ),
        migrations.RemoveField(
            model_name='roundpan',
            name='pan_type',
        ),
        migrations.RemoveField(
            model_name='squarepan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='squarepan',
            name='pan_name',
        ),
        migrations.RemoveField(
            model_name='squarepan',
            name='pan_type',
        ),
    ]
