# Generated by Django 4.2.6 on 2025-07-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='store',
            name='unique_store_per_location',
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('store_name', 'city', 'zip_code', 'address'), name='unique_store_per_location'),
        ),
    ]
