# Generated by Django 4.2.6 on 2025-03-23 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pan",
            name="number_of_pans",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
