# Generated by Django 4.2.6 on 2025-02-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="label_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
