# Generated by Django 4.2.6 on 2025-03-02 13:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="brand_name",
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="quantity",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="unit",
            field=models.TextField(
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Milliliters"),
                    ("cl", "Centiliters"),
                    ("l", "Liters"),
                    ("tsp", "Teaspoons"),
                    ("tbsp", "Tablespoons"),
                    ("cas", "Cuillère à soupe"),
                    ("cc", "Cuillère à café"),
                    ("cup", "Cups"),
                    ("unit", "Unit"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientpricehistory",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "store", "brand_name", "quantity", "unit"),
                name="unique_ingredient_price_history",
            ),
        ),
    ]
