# Generated by Django 4.2.6 on 2025-03-23 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0002_pan_number_of_pans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="avg_density",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="default_servings",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="default_volume",
        ),
        migrations.AddField(
            model_name="recipe",
            name="context_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="labels",
            field=models.ManyToManyField(
                related_name="recipes",
                through="pastry_app.RecipeLabel",
                to="pastry_app.label",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_type",
            field=models.CharField(
                choices=[("BASE", "Recette de base"), ("VARIATION", "Variante")],
                default="BASE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="chef_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("recipe_name", "chef_name", "context_name"),
                name="unique_recipe_per_context",
            ),
        ),
    ]
