# Generated by Django 4.2.6 on 2025-03-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0002_alter_category_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("ingredient", "Ingrédient"),
                    ("recipe", "Recette"),
                    ("both", "Les deux"),
                ],
                max_length=10,
            ),
        ),
    ]
