# Generated by Django 4.2.6 on 2025-03-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0002_alter_ingredientpricehistory_brand_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientpricehistory",
            name="ingredient_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pastry_app.ingredient",
            ),
        ),
    ]
