# Generated by Django 4.2.6 on 2025-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='subrecipe',
            index=models.Index(fields=['sub_recipe'], name='idx_subrecipe_on_sub'),
        ),
        migrations.AddIndex(
            model_name='subrecipe',
            index=models.Index(fields=['recipe'], name='idx_subrecipe_on_host'),
        ),
    ]
