# Generated by Django 4.2.6 on 2025-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0002_rename_number_of_pans_pan_units_in_mold_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="store",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                fields=("store_name", "city", "zip_code"),
                name="unique_store_per_location",
            ),
        ),
    ]
