# Generated by Django 4.2.6 on 2025-07-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0002_remove_store_unique_store_per_location_store_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientpricehistory',
            options={'verbose_name_plural': 'ingredient prices history'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
