# Generated by Django 4.2.6 on 2025-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0002_alter_category_category_name_alter_label_label_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=200),
        ),
    ]
