# Generated by Django 4.2.6 on 2025-08-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0003_alter_ingredientprice_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='adaptation_note',
            new_name='version_note',
        ),
    ]
