# Generated by Django 4.2.6 on 2025-07-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0003_alter_ingredientpricehistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientprice',
            name='unique_ingredient_price',
        ),
        migrations.AddConstraint(
            model_name='ingredientprice',
            constraint=models.UniqueConstraint(fields=('ingredient', 'store', 'brand_name', 'quantity', 'unit', 'date'), name='unique_ingredient_price'),
        ),
    ]
