# Generated by Django 4.2.6 on 2025-03-24 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0003_remove_recipe_avg_density_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="servings",
            new_name="servings_max",
        ),
        migrations.AddField(
            model_name="recipe",
            name="servings_min",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
