# Generated by Django 4.2.6 on 2025-03-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0003_ingredientpricehistory_ingredient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="trick",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="pastry_app.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="trick",
            field=models.TextField(blank=True, null=True),
        ),
    ]
