# Generated by Django 4.2.6 on 2025-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0003_alter_store_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recipe",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="recipestep",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="recipestep",
            constraint=models.UniqueConstraint(
                fields=("recipe", "step_number"), name="unique_step_per_recipe"
            ),
        ),
    ]
