# Generated by Django 4.2.6 on 2025-02-12 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0004_ingredientcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IngredientCategory",
        ),
    ]
