# Generated by Django 4.2.6 on 2025-03-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0004_alter_category_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientprice",
            name="brand_name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ingredientprice",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Milliliters"),
                    ("cl", "Centiliters"),
                    ("l", "Liters"),
                    ("tsp", "Teaspoons"),
                    ("tbsp", "Tablespoons"),
                    ("cas", "Cuillère à soupe"),
                    ("cc", "Cuillère à café"),
                    ("cup", "Cups"),
                    ("unit", "Unit"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="brand_name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Milliliters"),
                    ("cl", "Centiliters"),
                    ("l", "Liters"),
                    ("tsp", "Teaspoons"),
                    ("tbsp", "Tablespoons"),
                    ("cas", "Cuillère à soupe"),
                    ("cc", "Cuillère à café"),
                    ("cup", "Cups"),
                    ("unit", "Unit"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pan",
            name="pan_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_name",
            field=models.CharField(max_length=200),
        ),
    ]
