# Generated by Django 4.2.6 on 2025-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0004_alter_recipe_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("recipe_name", "chef_name"), name="unique_recipe_chef"
            ),
        ),
    ]
