# Generated by Django 4.2.6 on 2025-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0005_delete_ingredientcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="categories",
            field=models.ManyToManyField(
                related_name="recipes", to="pastry_app.category"
            ),
        ),
    ]
