# Generated by Django 4.2.6 on 2025-03-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0005_alter_ingredientprice_brand_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="chef_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
