# Generated by Django 4.2.6 on 2025-06-29 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastry_app', '0005_recipe_unique_recipe_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privée'), ('public', 'Publique')], default='private', max_length=10),
        ),
    ]
