# Generated by Django 4.2.6 on 2025-07-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0005_remove_ingredientprice_unique_ingredient_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe_chef',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='context_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
