# Generated by Django 4.2.6 on 2025-02-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0006_recipe_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="chef",
            field=models.CharField(default="Anonyme", max_length=200),
        ),
    ]
