# Generated by Django 4.2.6 on 2025-07-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0007_alter_recipestep_step_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'recipe category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='recipelabel',
            options={'verbose_name': 'recipe labels', 'verbose_name_plural': 'labels'},
        ),
    ]
