# Generated by Django 4.2.6 on 2025-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0007_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
