# Generated by Django 4.2.6 on 2025-02-13 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0007_alter_recipe_chef"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="panserving",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="recipe_type",
        ),
        migrations.RemoveField(
            model_name="panserving",
            name="recipe_type",
        ),
    ]
