# Generated by Django 4.2.6 on 2025-06-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0007_alter_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
