# Generated by Django 4.2.6 on 2025-07-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0008_alter_recipecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_recipe_quantity',
            field=models.FloatField(blank=True, help_text='Quantité totale en g produite par cette recette (ex: 1200 pour 1200g de crème pâtissière)', null=True),
        ),
    ]
