# Generated by Django 4.2.6 on 2025-02-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0009_recipecategory_ingredientcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pastry_app.label')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastry_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastry_app.ingredient')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pastry_app.label')),
            ],
        ),
    ]
