# Generated by Django 4.2.6 on 2025-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0009_category_is_default_ingredient_guest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='adaptation_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
