# Generated by Django 4.2.6 on 2025-08-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0009_recipe_total_recipe_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientUnitReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('cl', 'Centiliters'), ('l', 'Liters'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('cas', 'Cuillère à soupe'), ('cc', 'Cuillère à café'), ('cup', 'Cups'), ('unit', 'Unit')], help_text='Unité (ex : unité, cas, cc, cup, tranche, etc.)', max_length=20)),
                ('weight_in_grams', models.FloatField(help_text='Poids en grammes correspondant à 1 unité de cet ingrédient.')),
                ('notes', models.CharField(blank=True, help_text='Commentaire, astuce ou source (optionnel).', max_length=200)),
                ('ingredient', models.ForeignKey(help_text='Ingrédient concerné', on_delete=django.db.models.deletion.CASCADE, related_name='unit_references', to='pastry_app.ingredient')),
            ],
            options={
                'verbose_name': 'Référence de conversion unité ➔ poids',
                'verbose_name_plural': 'Références de conversion unité ➔ poids',
                'ordering': ['ingredient', 'unit'],
                'unique_together': {('ingredient', 'unit')},
            },
        ),
    ]
