# Generated by Django 4.2.6 on 2025-07-03 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastry_app', '0010_recipe_adaptation_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipeVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastry_app.recipe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'guest_id', 'recipe')},
            },
        ),
    ]
