# Generated by Django 4.2.6 on 2025-08-03 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastry_app', '0010_ingredientunitreference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientunitreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ingredientunitreference',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ingredientunitreference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_unit_references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientunitreference',
            unique_together={('ingredient', 'unit', 'user', 'guest_id')},
        ),
    ]
