# Generated by Django 4.2.6 on 2025-02-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0010_recipelabel_ingredientlabel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientprice",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="pastry_app.ingredient",
            ),
        ),
    ]
