# Generated by Django 4.2.6 on 2025-02-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0011_alter_ingredientprice_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="pastry_app.RecipeIngredient",
                to="pastry_app.ingredient",
            ),
        ),
    ]
