# Generated by Django 4.2.6 on 2025-07-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0011_userrecipevisibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientprice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='pastry_app.store'),
        ),
    ]
