# Generated by Django 4.2.6 on 2025-08-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0011_alter_ingredientunitreference_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientunitreference',
            constraint=models.UniqueConstraint(fields=('ingredient', 'unit', 'user', 'guest_id'), name='unique_ingredient_unit_user_guest'),
        ),
    ]
