# Generated by Django 4.2.6 on 2025-07-07 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0012_alter_ingredientprice_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='label',
            name='is_default',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
