# Generated by Django 4.2.6 on 2025-02-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0012_alter_ingredient_ingredient_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pastry_app.recipe"
            ),
        ),
    ]
