# Generated by Django 4.2.6 on 2025-08-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0012_ingredientunitreference_unique_ingredient_unit_user_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientunitreference',
            options={'ordering': ['ingredient', 'unit', 'is_hidden'], 'verbose_name': 'Référence de conversion unité ➔ poids', 'verbose_name_plural': 'Références de conversion unité ➔ poids'},
        ),
        migrations.AddField(
            model_name='ingredientunitreference',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Masque cette référence (soft-delete pour forker une globale)'),
        ),
    ]
