# Generated by Django 4.2.6 on 2025-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0013_alter_ingredientunitreference_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientunitreference',
            name='unique_ingredient_unit_user_guest',
        ),
        migrations.AddConstraint(
            model_name='ingredientunitreference',
            constraint=models.UniqueConstraint(fields=('ingredient', 'unit', 'user', 'guest_id', 'is_hidden'), name='unique_ingredient_unit_user_guest_hidden'),
        ),
    ]
