# Generated by Django 4.2.6 on 2025-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0014_remove_ingredientunitreference_unique_ingredient_unit_user_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientprice',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligrams'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('cl', 'Centiliters'), ('l', 'Liters'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('cas', 'Cuillère à soupe'), ('cac', 'Cuillère à café'), ('cup', 'Cups'), ('unit', 'Unit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredientpricehistory',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligrams'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('cl', 'Centiliters'), ('l', 'Liters'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('cas', 'Cuillère à soupe'), ('cac', 'Cuillère à café'), ('cup', 'Cups'), ('unit', 'Unit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredientunitreference',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligrams'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('cl', 'Centiliters'), ('l', 'Liters'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('cas', 'Cuillère à soupe'), ('cac', 'Cuillère à café'), ('cup', 'Cups'), ('unit', 'Unit')], help_text='Unité (ex : unité, cas, cc, cup, tranche, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligrams'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('cl', 'Centiliters'), ('l', 'Liters'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('cas', 'Cuillère à soupe'), ('cac', 'Cuillère à café'), ('cup', 'Cups'), ('unit', 'Unit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subrecipe',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligrams'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('cl', 'Centiliters'), ('l', 'Liters'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('cas', 'Cuillère à soupe'), ('cac', 'Cuillère à café'), ('cup', 'Cups'), ('unit', 'Unit')], max_length=50),
        ),
    ]
