# Generated by Django 4.2.6 on 2025-02-19 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0014_alter_recipeingredient_ingredient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredientprice",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="ingredientprice",
            name="city",
        ),
        migrations.RemoveField(
            model_name="ingredientprice",
            name="store_name",
        ),
        migrations.RemoveField(
            model_name="ingredientprice",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="ingredientprice",
            name="brand_name",
            field=models.TextField(blank=True, default="Non renseigné", max_length=200),
        ),
        migrations.AddField(
            model_name="ingredientprice",
            name="is_promo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ingredientprice",
            name="promotion_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingredientprice",
            name="unit",
            field=models.TextField(
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Milliliters"),
                    ("cl", "Centiliters"),
                    ("l", "Liters"),
                    ("tsp", "Teaspoons"),
                    ("tbsp", "Tablespoons"),
                    ("cas", "Cuillère à soupe"),
                    ("cc", "Cuillère à café"),
                    ("cup", "Cups"),
                    ("unit", "Unit"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(default="Non renseigné", max_length=200),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["store_name", "city", "zip_code"],
                        name="pastry_app__store_n_cde1df_idx",
                    )
                ],
                "unique_together": {("store_name", "city", "zip_code")},
            },
        ),
        migrations.CreateModel(
            name="IngredientPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("is_promo", models.BooleanField(default=False)),
                (
                    "ingredient_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="pastry_app.ingredientprice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ingredientprice",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="pastry_app.store",
            ),
        ),
    ]
