# Generated by Django 4.2.6 on 2025-02-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0015_remove_ingredientprice_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="store_name",
            field=models.CharField(max_length=200),
        ),
    ]
