# Generated by Django 4.2.6 on 2025-08-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0015_alter_ingredientprice_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrecipe',
            name='unit',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('cl', 'cl'), ('l', 'l')], max_length=50),
        ),
    ]
