# Generated by Django 4.2.6 on 2025-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0016_alter_store_store_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientprice",
            name="brand_name",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
