# Generated by Django 4.2.6 on 2025-08-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0016_alter_subrecipe_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='owned_by_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_variants', to='pastry_app.recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('owned_by_recipe', None), _negated=True), models.Q(('parent_recipe', None), _negated=True)), fields=('owned_by_recipe', 'parent_recipe'), name='uniq_owned_variant_per_host_and_source'),
        ),
    ]
