# Generated by Django 4.2.6 on 2025-08-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_app', '0017_recipe_owned_by_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='category_name'),
        ),
    ]
