# Generated by Django 4.2.6 on 2025-02-26 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0017_alter_ingredientprice_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientpricehistory",
            name="brand_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ingredientpricehistory",
            name="ingredient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pastry_app.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="ingredientpricehistory",
            name="promotion_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingredientpricehistory",
            name="quantity",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="ingredientpricehistory",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pastry_app.store",
            ),
        ),
        migrations.AddField(
            model_name="ingredientpricehistory",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Milliliters"),
                    ("cl", "Centiliters"),
                    ("l", "Liters"),
                    ("tsp", "Teaspoons"),
                    ("tbsp", "Tablespoons"),
                    ("cas", "Cuillère à soupe"),
                    ("cc", "Cuillère à café"),
                    ("cup", "Cups"),
                    ("unit", "Unit"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="price",
            field=models.FloatField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientpricehistory",
            constraint=models.UniqueConstraint(
                fields=("ingredient_price", "date"),
                name="unique_ingredientpricehistory",
            ),
        ),
    ]
