# Generated by Django 4.2.6 on 2025-02-26 20:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0018_ingredientpricehistory_brand_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pastry_app.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="price",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Milliliters"),
                    ("cl", "Centiliters"),
                    ("l", "Liters"),
                    ("tsp", "Teaspoons"),
                    ("tbsp", "Tablespoons"),
                    ("cas", "Cuillère à soupe"),
                    ("cc", "Cuillère à café"),
                    ("cup", "Cups"),
                    ("unit", "Unit"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
