# Generated by Django 4.2.6 on 2025-02-26 20:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pastry_app", "0019_alter_ingredientpricehistory_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="ingredient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pastry_app.ingredient",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="price",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="quantity",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredientpricehistory",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("ml", "Milliliters"),
                    ("cl", "Centiliters"),
                    ("l", "Liters"),
                    ("tsp", "Teaspoons"),
                    ("tbsp", "Tablespoons"),
                    ("cas", "Cuillère à soupe"),
                    ("cc", "Cuillère à café"),
                    ("cup", "Cups"),
                    ("unit", "Unit"),
                ],
                default="kg",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
